export * from './About'
export * from './Home'
export * from './Products'
export * from './NotFound'
export * from './ProductDetails'
export * from './Register'
export * from './Login'
export * from './Tasks'